#!/usr/bin/env node
// Assembles the hosted-platform bundle for Shellfire Isles:
//
//   dist-deploy/
//     logic.js          data.js + engine.js + arena rules, one self-contained module
//     index.html        the Arena (multiplayer battle & trade client)
//     assets/
//       adventure.html  the solo adventure (renamed game.html)
//       css/…  js/…     shared modules, referenced relatively
//
// Usage: node build-deploy.mjs   → dist-deploy/ + shellfire-isles.zip

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(ROOT, 'dist-deploy');
const PUB = path.join(ROOT, 'public');

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, 'assets'), { recursive: true });

// ---- logic.js: inline data + engine + arena rules (sandbox allows no imports)
const strip = src => src
  .split('\n')
  .filter(line => !/^import\s/.test(line))
  .join('\n')
  .replace(/^export /gm, '');

const data = strip(fs.readFileSync(path.join(PUB, 'js/data.js'), 'utf8'));
const engine = strip(fs.readFileSync(path.join(PUB, 'js/engine.js'), 'utf8'));
const arena = fs.readFileSync(path.join(ROOT, 'arena/arena-logic.js'), 'utf8')
  .split('\n').filter(line => !/^import\s/.test(line)).join('\n'); // keep its exports

fs.writeFileSync(path.join(OUT, 'logic.js'), [
  '// Shellfire Isles Arena — generated by build-deploy.mjs; edit the sources instead.',
  '// ===== data.js =====', data,
  '// ===== engine.js =====', engine,
  '// ===== arena rules =====', arena,
].join('\n'));

// ---- arena client
fs.copyFileSync(path.join(ROOT, 'arena/index.html'), path.join(OUT, 'index.html'));

// ---- adventure + shared assets under assets/
fs.cpSync(path.join(PUB, 'js'), path.join(OUT, 'assets/js'), { recursive: true });
fs.cpSync(path.join(PUB, 'css'), path.join(OUT, 'assets/css'), { recursive: true });

let adventure = fs.readFileSync(path.join(PUB, 'game.html'), 'utf8');
adventure = adventure
  .replace('<title>Shellfire Isles — Adventure</title>',
           '<title>Shellfire Isles — Adventure</title>\n<base href="./">')
  .replaceAll('href="index.html"', 'href="../"')
  .replaceAll('href="hub.html" target="_blank"', 'href="../" target="_blank"');
fs.writeFileSync(path.join(OUT, 'assets/adventure.html'), adventure);

// the in-game "Island Link" buttons should open the Arena (one level up)
const gamejs = path.join(OUT, 'assets/js/game.js');
fs.writeFileSync(gamejs, fs.readFileSync(gamejs, 'utf8').replaceAll("window.open('hub.html', '_blank')", "window.open('../', '_blank')"));

// hub.js is only used by the self-hosted flavor; keep the bundle lean
fs.rmSync(path.join(OUT, 'assets/js/hub.js'), { force: true });

// ---- zip it (contents at archive root, per the platform layout)
const zipPath = path.join(ROOT, 'shellfire-isles.zip');
fs.rmSync(zipPath, { force: true });
execSync(`cd "${OUT}" && zip -qr "${zipPath}" .`, { stdio: 'inherit' });
console.log('bundle ready:', zipPath);
console.log(execSync(`unzip -l "${zipPath}"`).toString());
