/**
 * Generates src/data/content/legal/legalText.ts from the canonical Markdown
 * files (disclaimer.md, terms.md, privacy.md).
 *
 * The Markdown files are the human-editable source of truth. React Native's
 * bundler can't import .md directly without a transformer, so we embed the text
 * as a plain TS string module. Edit the .md files, then run:  npm run sync:legal
 *
 * LEGAL REVIEW REQUIRED: the disclaimer, Terms, and Privacy Policy are
 * placeholders and must be reviewed by a licensed attorney before release.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const legalDir = join(here, '..', 'src', 'data', 'content', 'legal');

const docs = {
  disclaimerMarkdown: 'disclaimer.md',
  termsMarkdown: 'terms.md',
  privacyMarkdown: 'privacy.md',
};

const parts = Object.entries(docs).map(([exportName, file]) => {
  const text = readFileSync(join(legalDir, file), 'utf8');
  return `export const ${exportName} = ${JSON.stringify(text)};`;
});

const banner = `/**
 * AUTO-GENERATED by scripts/syncLegal.mjs — do not edit by hand.
 * Edit the Markdown source files in this folder, then run: npm run sync:legal
 *
 * Placeholder legal copy. A licensed attorney must review the disclaimer, Terms
 * of Service, and Privacy Policy before release. Not legal advice.
 */
`;

writeFileSync(join(legalDir, 'legalText.ts'), banner + '\n' + parts.join('\n\n') + '\n');
console.log('Wrote src/data/content/legal/legalText.ts from Markdown sources.');
